version: '3'
services:
  server_rpc:
    build: .
    ports:
      - ${RPC_PORT}:${RPC_PORT}
    container_name: ${APP_NAME}
    volumes:
      - ".env:/server_app/.env"
    networks:
      - myNetwork 
      - myNetworkDB

networks:
  myNetworkDB:
    
  myNetwork:
    name: local