version: '3'
services:
  server_rpc:
    build: .
    ports:
      - ${RPC_PORT}:${RPC_PORT}
    container_name: ${APP_NAME}
    volumes:
      - ".env:/server_app/.env"
    networks:
      - myNetwork 
      - myNetworkDB

  db:
    image: postgres:14.4-alpine
    container_name: postgres_users
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - 5454:5432
    networks:
      - myNetworkDB

networks:
  myNetworkDB:
    
  myNetwork:
    name: local